### ISSUE TITLE
Add Cylinder

### ISSUE THREAD

**Issue by Bikram-ghuku** [Bikram-ghuku/shapes#5]
Add cylinder to the supported shapes
Following functions should work

-> Lateral Surface area
-> Total Surface Area
-> Volume

**Comment by codygula** [comment]
Can I give this a try?

**Comment by Bikram-ghuku** [comment]
> Can I give this a try?

Yup sure go ahead...

**Comment by Bikram-ghuku** [comment]
Thanks to codygula for creating and adding the cylinder support to our shapes library.
